// src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import HeroSection from './components/HeroSection.vue'
import FeaturedProject from './components/FeaturedProject.vue'
import StatsBar from './components/StatsBar.vue'
import FilterBar from './components/FilterBar.vue'
import ProjectGrid from './components/ProjectGrid.vue'
import TechStackSection from './components/TechStackSection.vue'
import SiteFooter from './components/SiteFooter.vue'
import { projects } from './data/projects'
import { useI18n } from './composables/useI18n'

const { locale } = useI18n()

const selectedCategory = ref<string | null>(null)
const searchQuery = ref('')

const filteredProjects = computed(() => {
  let result = projects

  if (selectedCategory.value) {
    result = result.filter(p => p.category === selectedCategory.value)
  }

  const q = searchQuery.value.trim().toLowerCase()
  if (q) {
    result = result.filter(p =>
      p.name[locale.value].toLowerCase().includes(q) ||
      p.description[locale.value].toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q))
    )
  }

  return result
})
</script>

<template>
  <HeroSection />
  <FeaturedProject />
  <StatsBar />
  <FilterBar
    v-model:selectedCategory="selectedCategory"
    v-model:searchQuery="searchQuery"
  />
  <ProjectGrid :projects="filteredProjects" />
  <TechStackSection />
  <SiteFooter />
</template>

// src/app/page.tsx
'use client'

import { useState, useMemo } from 'react'
import { useI18n } from '@/lib/i18n'
import { projects } from '@/data/projects'
import { categories } from '@/data/categories'
import { techTags, techTagMap } from '@/data/tech-tags'
import { Hero } from '@/components/hero'
import { StatsBar } from '@/components/stats-bar'
import { FeaturedProject } from '@/components/featured-project'
import { FilterBar } from '@/components/filter-bar'
import { ProjectList } from '@/components/project-list'
import { TechStack } from '@/components/tech-stack'
import { SiteFooter } from '@/components/site-footer'

export default function Home() {
  const { locale } = useI18n()
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')

  const filteredProjects = useMemo(() => {
    let result = projects
    if (selectedCategory) {
      result = result.filter(p => p.category === selectedCategory)
    }
    const q = searchQuery.trim().toLowerCase()
    if (q) {
      result = result.filter(p =>
        p.name[locale].toLowerCase().includes(q) ||
        p.description[locale].toLowerCase().includes(q) ||
        p.tags.some(t => {
          const tag = techTagMap[t]
          return tag?.label.toLowerCase().includes(q)
        })
      )
    }
    return result
  }, [selectedCategory, searchQuery, locale])

  const techUsage = useMemo(() => {
    const counts: Record<string, number> = {}
    for (const p of projects) {
      for (const t of p.tags) {
        counts[t] = (counts[t] || 0) + 1
      }
    }
    return techTags
      .map(t => ({ ...t, count: counts[t.id] || 0 }))
      .filter(t => t.count > 0)
      .sort((a, b) => b.count - a.count)
  }, [])

  const featured = projects.find(p => p.id === 'smart-factory-demo')!

  return (
    <div className="max-w-[920px] mx-auto px-8">
      <Hero />
      <div className="divider" />
      <StatsBar
        projectCount={projects.length}
        categoryCount={categories.length}
        techCount={techUsage.length}
      />
      <div className="divider" />
      <FeaturedProject project={featured} />
      <div className="divider" />
      <FilterBar
        categories={categories}
        selectedCategory={selectedCategory}
        onCategoryChange={setSelectedCategory}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
      />
      <ProjectList projects={filteredProjects} />
      <div className="divider" />
      <TechStack items={techUsage} />
      <SiteFooter />
    </div>
  )
}
